language: node_js
node_js:
  - "node"
  - "8"
  - "7"
  - "6"
before_script:
  - "cp config.js.template config.js"
after_success: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
branches:
  only:
    - improvement/jpajuelo-contrib